---
name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout with history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run super-linter
        uses: super-linter/super-linter/slim@v7.4.0
        env:
          # super-linter configurations
          MULTI_STATUS: false
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          # language configurations
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # misc configurations
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          VALIDATE_GIT_COMMITLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true

  lint-success:
    needs: lint

    name: Lint success
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Dispatch super-linter-success
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'super-linter-success',
            })
